### ISSUE TITLE
Examples how to use?

### ISSUE THREAD

**Issue by ron819** [singer-io/tap-bronto#9]
Is it possible to post some examples how to use this Contacts with Filters?

**Comment by ron819** [comment]
An actual example with say `modified` filter ? This param is for the `make_filter` function.
Can you also explain how this lib parse the `readOnlyContactData` object? 
https://help.bronto.com/bmp/reference/r_api_soap_settings_readonlycontactdata.html

The:
```
                    results = self.client.service.readContacts(
                        filter=_filter,
                        includeLists=True,
                        fields=[],
                        pageNumber=pageNumber,
                        includeSMSKeywords=True,
                        includeGeoIPData=includeGeoIpData,
                        includeTechnologyData=includeTechnologyData,
                        includeRFMData=includeRFMData,
                        includeEngagementData=includeEngagementData)
```

Gives object as:


```
(readOnlyContactData){
   geoIPCity = ""something""
   geoIPStateRegion = ""something""
   geoIPZip = ""something""
   geoIPCountry = ""United Kingdom""
   geoIPCountryCode = ""GB""
   primaryBrowser = ""Mobile Safari""
   mobileBrowser = ""Mobile Safari""
   primaryEmailClient = ""Unknown Webmail Client""
   mobileEmailClient = ""Unknown Webmail Client""
   operatingSystem = ""iOS""
   firstOrderDate = 2013-01-30 07:00:00-05:00
   lastOrderDate = 2017-03-01 20:01:47.476000-05:00
   lastOrderTotal = 19.45
   totalOrders = 314
   totalRevenue = 9873.42
   averageOrderValue = 31.444012
   lastDeliveryDate = 2018-11-16 04:41:39.883000-05:00
   lastOpenDate = 2017-06-17 18:35:57.070000-04:00
   lastClickDate = 2017-06-17 18:37:28.166000-04:00
 }
```
How do you parse this object? It's not a list nor a dict.. say the goal is to get a CSV file someone the 
geoIPCity, geoIPStateRegion should be converted to columns.

**Comment by dmosorast** [comment]
It seems that the README could be modified to include descriptions of the required config keys, mentioned [here](https://github.com/singer-io/tap-bronto/blob/master/tap_bronto/__init__.py#L18). Since this tap is available to run in Stitch, using [that documentation](https://www.stitchdata.com/docs/integrations/saas/bronto) might be helpful in getting the token used for crafting the config file.

I'd be willing to accept a PR with descriptions of those keys added to the README.

**Comment by nick-mccoy** [comment]
Closing this.  If it is revisited, a PR should be opened with the suggested changes.
